version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    command: >
      sh -c " sbt compile &&
              sbt flywayMigrate &&
              sbt run "
    depends_on:
      - db_vms
      - phpmyadmin
    environment:
      - TZ=Asia/Bangkok
  db_vms:
    image: mysql:8
    container_name: db_vms
    command: mysqld --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: chatapp
      MYSQL_USER: tao
      MYSQL_PASSWORD: tao@1234
      MYSQL_PORT: 3306
      TZ: Asia/Bangkok
    ports:
      - "6033:3306"
    volumes:
      - ./data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - db_vms
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80
    depends_on:
      - db_vms
